services:
  - type: web
    name: sdetrack
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: sdetrack
      - key: MONGO_COLLECTION_NAME
        value: questions
      - key: USER_ONE_NAME
        value: Me
      - key: USER_TWO_NAME
        value: Didi
